model_params:
  name: 'SBVAE'
  in_channels: 1
  latent_dim: 50

exp_params:
  dataset: mnist
  data_path: "temp_data"
  img_size: 28
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_epochs: 30

logging_params:
  save_dir: "/content/drive/'My Drive'/logs"
  name: "SBVAE"
  manual_seed: 1265